language: node_js
node_js:
- '5'
branches:
  only:
  - master
before_install:
- npm install
before_script:
- git config --global user.name 'j3lte via Travis CI'
- git config --global user.email 'jwlagendijk@gmail.com'
- sed -i'' "s~git@github.com:j3lte/blog.git~https://${GH_TOKEN}:x-oauth-basic@github.com/j3lte/blog.git~"
  _config.yml
install:
- npm run generate
script:
- npm run deploy
env:
  global:
    secure: O1rWVxFvAPdSnAoK6m/CAimzanKyLbcsF77dtTDUxXm0avwRvSJSxugVRwip/FmO/6s2duh/jSbrDXtiytNz6adv9W1LZ0poyrmtBjZ6BPA7jtJZsys1kYezHdr2goAuIinLd66nDaIld//8pcEs+OVczQtmfKX+OWTulB3LbyA=
